RachaelProject/Models/ContactListModel.cs
using System.ComponentModel.DataAnnotations;
using RachaelProject.Models;

namespace RachaelProject.Models
{
    public class ContactListModel
    {
        public IEnumerable<ContactListModel>? ContactList { get; set; }
        public int ContactId { get; set; }
        public string? FullName { get; set; }
        [DataType(DataType.EmailAddress)]
        public string? EmailAddress { get; set; }
        [DataType(DataType.PhoneNumber)]
        public string? PhoneNumber { get; set; }
    }
}

RachaelProject/Models/ErrorViewModel.cs
namespace RachaelProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RachaelProject/Models/ProductModel.cs
using System.ComponentModel;

namespace RachaelProject.Models
{
    public class ProductModel
    {
        public IEnumerable<ProductModel>? NewProduct { get; set; }
        [DisplayName("ProductId")]
        public int ProductId { get; set; }
        [DisplayName("Name")]
        public string? Name { get; set; }
        [DisplayName("Breed")]
        public string? Breed { get; set; }
        [DisplayName("Age")]
        public int Age { get; set; }
        [DisplayName("FavToy")] 
        public string? FavToy { get; set; }
        [DisplayName("About Me")]
        public string? Description { get; set; }
        public string? Image { get; set; }
        
    }
}

RachaelProject/Controllers/ContactListController.cs
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using RachaelProject.Models;

namespace RachaelProject.Controllers
{
    public class ContactListController : Controller
    {
        private readonly IContactListRepository repo;

        public ContactListController(IContactListRepository repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            var contact = repo.GetAllContacts();
            return View(contact);
        }
        public IActionResult ViewContact(int id)
        {
            var contact = repo.GetContactById(id);
            return View(contact);
        }
        public IActionResult UpdateContact(int id)
        {
            ContactListModel contact = repo.GetContactById(id);
            if (contact == null)
            {
                return View("ContactNotFound");
            }
            return View(contact);
        }
        public IActionResult UpdateContactToDatabase(ContactListModel contact)
        {
            repo.UpdateContact(contact);

            return RedirectToAction("ViewContact", new { id = contact.ContactId });
        }
        public IActionResult InsertContact()
        {
            var contact = repo.AssignContact();
            return View(contact);
        }
        public IActionResult InsertContactToDatabase(ContactListModel ContactToInsert)
        {
            repo.InsertContact(ContactToInsert);
            return RedirectToAction("Index");
        }
    }
}

RachaelProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RachaelProject.Models;
using System.Diagnostics;

namespace RachaelProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            ViewBag.Message = "I may change this page to something other than privacy.";
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RachaelProject/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using RachaelProject.Models;

namespace RachaelProject.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository repo;

        public ProductController(IProductRepository repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            var products = repo.GetAllProducts();
            return View(products);
        }
        public IActionResult UpdateProduct(int id)
        {
            ProductModel prod = repo.GetProductById(id);
            if (prod == null)
            {
                return View("PupNotFound");
            }
            return View(prod);
        }
        public IActionResult UpdateProductToDatabase(ProductModel product)
        {
            repo.Update(product);

            return RedirectToAction("ViewProduct", new { id = product.ProductId });
        }
        public IActionResult ViewProduct(int id)
        {
            var product = repo.GetProductById(id);
            return View(product);
        }
        public IActionResult Delete(ProductModel product)
        {
            repo.Delete(product);
            return RedirectToAction("Index");
        }
    }
}









RachaelProject/Views/ContactList/Index.cshtml
@model IEnumerable<ContactListModel>

<h2>ContactList</h2>
<div style="display: block">
    <a href="/ContactList/InsertContact/">Enter your Contact Information</a>
</div>
<table class="table">
    <tr>
        <th>ContactId</th>
        <th>FullName</th>
        <th>EmailAddress</th>
        <th>PhoneNumber</th>
    </tr>

    @foreach (var contact in @Model)
    {
        <tr>
            <td><a href=/ContactList/ViewProduct/@contact.ContactId>@contact.ContactId</a></td>
            <td>@contact.FullName</td>
            <td>@contact.EmailAddress</td>
            <td>@contact.PhoneNumber</td>
        </tr>
    }

</table>
            

RachaelProject/Views/ContactList/InsertContact.cshtml
@model RachaelProject.Models.ContactListModel

<h2>Enter your Contact Information</h2>

@using (Html.BeginForm("InsertContactToDatabase", "contactlist", "Post"))
{
    <input asp-for="ContactId" type="hidden" value="" />

    <label asp-for="FullName" class="control-label">Full Name</label>
    <input type="text" name="FullName" class="form-control" value="" />

    <label asp-for="EmailAddress" class="control-label">Email Address</label>
    <input type="email" step="0.01" name="EmailAddress" class="form-control" />

    <label asp-for="PhoneNumber" class="control-label">Phone Number</label>
    <input type="text" step="0.01" name="PhoneNumber" class="form-control" />

    <input type="submit" value="Create Contact" class="btn btn-primary" />
  

}

RachaelProject/Views/ContactList/UpdateContact.cshtml
@model ContactListModel

<h2>Update @Model.FullName</h2>

@using (Html.BeginForm("UpdateContactToDatabase", "ContactList", "Post"))
{
    <input asp-for="ContactId" type="hidden" value="@Model.ContactId" />

    <label asp-for="FullName" class="control-label">FullName</label>
    <input type="text" name="FullName" class="form-control" value="@Model.FullName" />

    <label asp-for="EmailAddress" class="control-label">Email Address</label>
    <input type="email" step="0.01" name="EmailAddress" class="form-control" value="@Model.EmailAddress" />
    
    <label asp-for="PhoneNumber" class="control-label">Phone Number</label>
    <input type="tel" step="0.01" name="PhoneNumber" class="form-control" value="@Model.PhoneNumber" />

    <input type="submit" value="Update Contact" class="btn btn-primary" />
}

RachaelProject/Views/ContactList/ViewContact.cshtml
@model ContactListModel

<h3>@Model.FullName Information</h3>

<table class="table">
    <tr>
        <th>ContactId</th>
        <th>FullName</th>
        <th>EmailAddress</th>
        <th>PhoneNumber</th>
    </tr>
    <tr>
        <td>@Model.ContactId</td>
        <td>@Model.FullName</td>
        <td>@Model.EmailAddress</td>
        <td>@Model.PhoneNumber</td>
    </tr>
</table>

<div style="display: block">
    <a href="/ContactList/UpdateProduct/@Model.ContactId">Update this Contact</a>
</div>

        
        

RachaelProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
<div class="bg-image"
     style="
    background-image: url(https://images.pexels.com/photos/1904103/pexels-photo-1904103.jpeg?auto=compress&cs=tinysrgb&w=1600);
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center;
    height: 100vh;
    border: 0px;
     
  ">
        <div class="float-left"
        style="font-size:50px;">Sign to adopt today!
        </div><br>
        <div class="float-left"
             style="font-size:25px;">
            Click the adopt tab to see our dogs.
        </div><br>
        <!--<div class="overlay"></div>-->
    </div>
</div> 







RachaelProject/Views/Product/Delete.cshtml
@model RachaelProject.Models.ProductModel

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Breed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Breed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FavToy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FavToy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RachaelProject/Views/Product/Index.cshtml
@model IEnumerable<RachaelProject.Models.ProductModel>

<p>
    <a asp-action="Create">Create New</a>
</p>

<div class="container d-flex flex-wrap">

    @foreach (var item in Model)
    {
        <!--I created a column in MySQL for images of the dogs. I need to figure out how to properly point to the column in the foreach loop.-->
        <div class="card" style="width: 18rem;">
            <img src="https://loremflickr.com/200/200/@item.Breed?lock=@item.Breed" class="card-img-top" alt="@item.Breed">
            <div class="card-body">
                <h5 class="card-title">@item.Name</h5>
                <p class="card-text">@item.Breed</p>
                <p class="card-text">Age: @item.Age</p>
                <p class="card-text">Favorite toy: @item.FavToy</p>
                <p class="card-text">@item.Description</p>
                <a href="/contactlist/InsertContact/@item.ProductId" class="btn btn-primary">Adopt Me!</a>
            </div>
        </div>
    }
</div>
    



RachaelProject/Views/Product/UpdateProduct.cshtml
@model ProductModel

<h2>Update @Model.Name</h2>

@using (Html.BeginForm("UpdateProductToDatabase", "ProductModel", "Post"))
{
    <input asp-for="ProductId" type="hidden" value="@Model.ProductId" />

    <label asp-for="Name" class="control-label">Name</label>
    <input type="text" name="Name" class="form-control" value="@Model.Name" />

    <label asp-for="Breed" class="control-label">Breed</label>
    <input type="text" step="0.01" name="Breed" class="form-control" value="@Model.Breed" />

    <label asp-for="Age" class="control-label">Age</label>
    <input type="number" step="0.01" name="Age" class="form-control" value="@Model.Age" />

    <label asp-for="FavToy" class="control-label">FavToy</label>
    <input type="text" step="0.01" name="FavToy" class="form-control" value="@Model.FavToy" />

    <label asp-for="Description" class="control-label">Description</label>
    <input type="text" step="0.01" name="Description" class="form-control" value="@Model.Description" />

    <input type="submit" value="Update this Pup" class="btn btn-primary" />
}

RachaelProject/Views/Product/ViewProduct.cshtml
@model RachaelProject.Models.ProductModel

<div>
    <h4>ProductModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Breed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Breed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FavToy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FavToy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

RachaelProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RachaelProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RachaelProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @Html.Partial("_navbar.cshtml")
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RachaelProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RachaelProject/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RachaelProject</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="Index">Adopt</a>
                </li>
            </ul>
        </div>
    </div>
</nav>